version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - DATABASE_URL=postgresql://prog_z8hq_user:BJO5y77BbqQRHcx2BjsXEtV7t5R1O8kW@dpg-d0cjed15pdvs73a46480-a.oregon-postgres.render.com/prog_z8hq
